Trying out .NET Core on Travis.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -18,7 +18,7 @@ matrix:
       dist: trusty
       sudo: required
 
-install:
+before_install:
   - export DOTNET_SDK_URL="https://go.microsoft.com/fwlink/?LinkID=809129"
   - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
   - mkdir $DOTNET_INSTALL_DIR
@@ -26,6 +26,16 @@ install:
   - tar -xvzf dotnet_package -C $DOTNET_INSTALL_DIR
   - export PATH="$DOTNET_INSTALL_DIR:$PATH"
 
+install:
+  - which dotnet;
+    if [ $? -eq 0 ]; then
+      echo "Using dotnet:";
+      dotnet --info;
+    else
+      echo "dotnet.exe not found"
+      exit 1;
+    fi
+    
 before_script:
  - chmod +x ./build.sh
 
